Update der Systematik auf den Stand von 2023
dini-ag-kim/hochschulfaechersystematik pull request #28
Opened 2023-02-14 11:50 UTC by lummerland

Hier sind die Änderungen integriert, die in der aktuellen Veröffentlichung vom Januar 2023 (https://www.destatis.de/DE/Methoden/Klassifikationen/Bildung/studenten-pruefungsstatistik.html) enthalten sind. Außerdem auch die (umfangreicheren) vorhergehenden Änderungen vom 17.11.2021. Dazu finde ich allerdings gerade kein verlinkbares Dokument, ich habe das PDF bei mir lokal gespeichert :| Vielleicht kann das ja jemand nachrecherchieren?

Zwei Fächer sind gestrichen worden, ich habe sie als deprecated markiert. Ansonsten nur neue Fächer, Umbenennungen und Verschiebungen.

Betrifft Issue https://github.com/dini-ag-kim/hochschulfaechersystematik/issues/14.

2023-02-15 12:06 UTC, lummerland commented
FYI @TobiasNx @acka47

2023-03-21 10:09 UTC, lummerland commented
@acka47 Ich hab Antwort von destatis bekommen. Die Fächersystematik für WS2020/2021 ist unter https://www.statistischebibliothek.de/mir/receive/DEHeft_mods_00135733 zu finden :)

2023-12-08 16:35 UTC, mic-men approved these changes
Ist aus meiner Sicht in Ordnung, danke!

2023-12-11 14:59 UTC, acka47 commented
Ich habe mal draufgeschaut, allerdings ohne es 1-zu-1 mit der PDF-Version abzugleichen. Hier mein Bericht:

- Das turtle ist valide.
- Es sind nun 345 statt bisher 340 `ConceptScheme`s.

Allerdings meckert ein Build mit SkoHub Vocabs und, der Shacl-Check sagt viermal "Violation":

> Note should be provided with a language tag.

(Siehe auch https://skohub.io/build/?id=fdfba9db-a905-4b46-a7a6-6a7c89af95cd)

Es gibt aber nur zwei `skos:note`s, bei denen tatsächlich das language tag fehlt (@sroertgen, du weißt bestimmt eher, warum er aber vier Violations nennt):

- https://github.com/dini-ag-kim/hochschulfaechersystematik/blob/7af142f0e4caf81e3c8979c65702269c0cdadfbd/hochschulfaechersystematik.ttl#L1103
- https://github.com/dini-ag-kim/hochschulfaechersystematik/blob/7af142f0e4caf81e3c8979c65702269c0cdadfbd/hochschulfaechersystematik.ttl#L1635

Wenn du das noch korrigierst, sollte es passen, @lummerland .

2023-12-12 11:13 UTC, acka47 commented
Im [heutigen Treffen]() kam noch die Frage auf, was wir mit gelöschten/deprecated `skos:Concepts`s machen bzw. wie verarbeitende Systeme damit umgehen sollen. @mic-men, wir haben da ein bisschen aneinander vorbei geredet, weil es zwei verschiedene Fälle gibt.

### 1. deprecated: true

Es gibt zwei Fälle, in denen ein Konzept als deprecated markiert ist, siehe https://github.com/dini-ag-kim/hochschulfaechersystematik/pull/28/commits/7af142f0e4caf81e3c8979c65702269c0cdadfbd

Michaels Frage ging in die Richtung, wie Software-Implementierungen (u.U auch SkoHub) damit umgehen sollen. Z.B. sollen diese Werte ja nicht in Formularen zur Auswahl gestellt werden.

### 2. Löschung/Ersetzung einer Konzept-URI

Wenn ich das richtig sehe, gibt es dann noch einen einen Fall, wo eine Konzept-URI verschwindet, weil sie durch eine neue ersetzt wird:

https://github.com/dini-ag-kim/hochschulfaechersystematik/pull/28/files#diff-7faa76cd7d77a0b2a88e90859a93a364d0eaad01aa2f7e4250690de7be1b5f55L595-R603

Den zweiten Fall können wir vermeiden, indem wir weiter die alte URI verwenden, die dann halt nicht mit der Notation übereinstimmt. (Entstanden ist das Problem glaube ich, als in [diesem Commit](https://github.com/dini-ag-kim/hochschulfaechersystematik/commit/7eebae5327993bf498a2eb66aa8f18e4f2ac543c) nicht die URI mit aktualisiert wurde, sondern nur die Notation.) Ich verstehe, dass das gegen das ästhetische Empfinden verstößt, prinzipiell sollten wir aber dafür sorgen, dass URIs stabil bleiben.

2023-12-12 11:23 UTC, acka47 commented
Einen anderen Punkt habe ich im heutigen Treffen auch angesprochen: Wir müssten uns bei den stattgefundenen Anpassungen und Ergänzungen von Labels  auch um deren Übersetzungen kümmern (en, nl, uk) bzw. überlegen, wie wir damit umgehen.

2024-01-05 09:02 UTC, mic-men commented
> Im [heutigen Treffen](https://metadaten.community/t/online-treffen-der-oer-metadatengruppe/50) kam noch die Frage auf, was wir mit gelöschten/deprecated `skos:Concepts`s machen bzw. wie verarbeitende Systeme damit umgehen sollen. @mic-men, wir haben da ein bisschen aneinander vorbei geredet, weil es zwei verschiedene Fälle gibt.
> ### 1. deprecated: true
> 
> Es gibt zwei Fälle, in denen ein Konzept als deprecated markiert ist, siehe [7af142f](https://github.com/dini-ag-kim/hochschulfaechersystematik/commit/7af142f0e4caf81e3c8979c65702269c0cdadfbd)
> 
> Michaels Frage ging in die Richtung, wie Software-Implementierungen (u.U auch SkoHub) damit umgehen sollen. Z.B. sollen diese Werte ja nicht in Formularen zur Auswahl gestellt werden.

Genau, diesen Punkt würde ich gern besprechen. Sie dürfen nicht mehr auswählbar sein. Aber was ist mit vergebenen Werten? Sollen diese so bleiben oder auf andere abgebildet werden? Wenn letzteres, wie?

2024-01-08 08:42 UTC, lummerland commented
> Ich habe mal draufgeschaut, allerdings ohne es 1-zu-1 mit der PDF-Version abzugleichen. Hier mein Bericht:
> 
>     * Das turtle ist valide.
> 
>     * Es sind nun 345 statt bisher 340 `ConceptScheme`s.
> 
> 
> Allerdings meckert ein Build mit SkoHub Vocabs und, der Shacl-Check sagt viermal "Violation":
> 
> > Note should be provided with a language tag.
> 
> (Siehe auch https://skohub.io/build/?id=fdfba9db-a905-4b46-a7a6-6a7c89af95cd)
> 
> Es gibt aber nur zwei `skos:note`s, bei denen tatsächlich das language tag fehlt (@sroertgen, du weißt bestimmt eher, warum er aber vier Violations nennt):
> 
>     * https://github.com/dini-ag-kim/hochschulfaechersystematik/blob/7af142f0e4caf81e3c8979c65702269c0cdadfbd/hochschulfaechersystematik.ttl#L1103
> 
>     * https://github.com/dini-ag-kim/hochschulfaechersystematik/blob/7af142f0e4caf81e3c8979c65702269c0cdadfbd/hochschulfaechersystematik.ttl#L1635
> 
> 
> Wenn du das noch korrigierst, sollte es passen, @lummerland .

Die beiden Sprach-Tags sind integriert.

2024-01-08 08:50 UTC, lummerland commented
> ### 2. Löschung/Ersetzung einer Konzept-URI
> 
> Wenn ich das richtig sehe, gibt es dann noch einen einen Fall, wo eine Konzept-URI verschwindet, weil sie durch eine neue ersetzt wird:
> 
> https://github.com/dini-ag-kim/hochschulfaechersystematik/pull/28/files#diff-7faa76cd7d77a0b2a88e90859a93a364d0eaad01aa2f7e4250690de7be1b5f55L595-R603
> 
> Den zweiten Fall können wir vermeiden, indem wir weiter die alte URI verwenden, die dann halt nicht mit der Notation übereinstimmt. (Entstanden ist das Problem glaube ich, als in [diesem Commit](https://github.com/dini-ag-kim/hochschulfaechersystematik/commit/7eebae5327993bf498a2eb66aa8f18e4f2ac543c) nicht die URI mit aktualisiert wurde, sondern nur die Notation.) Ich verstehe, dass das gegen das ästhetische Empfinden verstößt, prinzipiell sollten wir aber dafür sorgen, dass URIs stabil bleiben.

Ich habe die Änderung der URI bzw. des Concept-Namens wieder rückgängig gemacht. Ich hatte nicht darüber nachgedacht was diese Änderung bedeutet. Ist aber auch gar nicht so einfach, wenn man einerseits die Concept-Namen sinnvoll vergeben will (statt z.B. unlesbare UUIDs oder dergleichen zu verwenden) aber andererseits damit auch für lange Zeit feste URIs definiert :)

2024-01-08 09:21 UTC, acka47 commented
> Ist aber auch gar nicht so einfach, wenn man einerseits die Concept-Namen sinnvoll vergeben will (statt z.B. unlesbare UUIDs oder dergleichen zu verwenden) aber andererseits damit auch für lange Zeit feste URIs definiert :)

Ja, da hast du Recht. Das kann schnell zu Konflikten kommen. Passenderweise werden die Notationen der Destatis-Systematik offensichtlich auch nie geändert, auch wenn eine Systemstelle komplett umgehängt wird. Deshalb fehlt da mittlerweile jede Konsistenz:

![image](https://github.com/dini-ag-kim/hochschulfaechersystematik/assets/160292/9928a968-940d-42f5-810f-97aef1b40016)

2024-01-08 09:57 UTC, acka47 commented on hochschulfaechersystematik.ttl
> +  skos:prefLabel "Orientierungsstudium MINT"@de ;
```suggestion
  skos:prefLabel "Orientierungsstudium MINT"@de "STEM orientation studies"@en ;
```

2024-01-08 09:58 UTC, acka47 commented on hochschulfaechersystematik.ttl
> +  skos:prefLabel "Orientierungsstudium Gesellschaftswissenschaften"@de ;
```suggestion
  skos:prefLabel "Orientierungsstudium Gesellschaftswissenschaften"@de , "Social sciences orientation studies"@en ;
```

2024-01-08 10:00 UTC, acka47 requested changes
Sieht alles gut aus. Ich habe jetzt noch zwei englische Labels vorgeschlagen für die neuen Concepts. Wenn du die noch ergänzt, gebe ich grünes Licht und merge das. (Hätte auch selbst commitet aber schaffe ich das nicht, weil der Branch nicht hier im Repo ist. Sollte eigentlich gehen, aber ich habe es jetzt aufgegeben. Wenn du den PR nächstes Mal von einem Branch aus diesem Repo aufmachst, wird das leichter.)

2024-01-08 10:41 UTC, lummerland commented
@acka47 Ergänzungen sind drin, danke dir! Ja, ich weiß auch nicht, warum ich den Weg über den Fork gegangen bin. Werde ich aber nicht mehr tun, sorry :)

2024-01-08 11:13 UTC, merged